# Site settings
title: Dossier visuel de Martin Lemaire 
tagline: ""
url: "" 

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
